[tool.poetry]
name = "supermechs"
version = "0.1.0"
description = "Package modeling the behavior of the SuperMechs game into python objects."
authors = ["Eneg"]
readme = "README.md"
packages = [
    {include = "supermechs", from = "src"}
]


[tool.poetry.dependencies]
python = "^3.10"
typing-extensions = "^4.4.1" # override
attrs = ">= 22.1.0" # min_len
Pillow = "^9.0.0"
# orjson = "*"
# git+https://github.com/Enegg/python-socketio
# aiohttp


[tool.poetry.group.dev.dependencies]
ruff = "^0.0.270"
black = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
select = ["E", "F", "TCH", "PTH", "RUF", "ASYNC"]

line-length = 100
target-version = "py310"


[tool.ruff.per-file-ignores]
"__init__.py" = ["F403"]
"api.py" = ["F403"]


[tool.ruff.isort]
combine-as-imports = true
forced-separate = ["supermechs"]


[tool.ruff.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]


[tool.pyright]
typeCheckingMode = "strict"
include = ["src/supermechs"]

pythonVersion = "3.10"

reportUnnecessaryTypeIgnoreComment = "info"
reportUnnecessaryCast = true
reportMatchNotExhaustive = "warning"
reportUnusedImport = true

reportOverlappingOverload = false
reportPrivateUsage = false
reportUnnecessaryIsInstance = false
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false

reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false
reportMissingTypeStubs = false
