from collections import abc
from typing import NewType, Protocol

__all__ = (
    "HasStages",
    "HasStats",
    "ItemData",
    "ItemData",
    "ItemElement",
    "ItemID",
    "ItemPaint",
    "ItemStats",
    "ItemTag",
    "ItemType",
    "StageLevel",
    "StageTier",
    "TransformStage",
)


ItemID = NewType("ItemID", str)
ItemType = NewType("ItemType", str)
ItemElement = NewType("ItemElement", str)
ItemTag = NewType("ItemTag", str)
ItemPaint = NewType("ItemPaint", str)


StageTier = NewType("StageTier", str)


class ItemStats(Protocol):
    @property
    def weight(self) -> float: ...
    @property
    def hit_points(self) -> float: ...
    @property
    def energy_capacity(self) -> float: ...
    @property
    def regeneration(self) -> float: ...
    @property
    def heat_capacity(self) -> float: ...
    @property
    def cooling(self) -> float: ...
    @property
    def physical_resistance(self) -> float: ...
    @property
    def explosive_resistance(self) -> float: ...
    @property
    def electric_resistance(self) -> float: ...
    @property
    def bullets_capacity(self) -> float: ...
    @property
    def rockets_capacity(self) -> float: ...
    @property
    def walk(self) -> float: ...
    @property
    def jump(self) -> float: ...
    @property
    def physical_damage(self) -> float: ...
    @property
    def physical_damage_addon(self) -> float: ...
    @property
    def physical_resistance_damage(self) -> float: ...
    @property
    def electric_damage(self) -> float: ...
    @property
    def electric_damage_addon(self) -> float: ...
    @property
    def energy_damage(self) -> float: ...
    @property
    def energy_capacity_damage(self) -> float: ...
    @property
    def regeneration_damage(self) -> float: ...
    @property
    def electric_resistance_damage(self) -> float: ...
    @property
    def explosive_damage(self) -> float: ...
    @property
    def explosive_damage_addon(self) -> float: ...
    @property
    def heat_damage(self) -> float: ...
    @property
    def heat_capacity_damage(self) -> float: ...
    @property
    def cooling_damage(self) -> float: ...
    @property
    def explosive_resistance_damage(self) -> float: ...
    @property
    def range(self) -> float: ...
    @property
    def range_addon(self) -> float: ...
    @property
    def push(self) -> float: ...
    @property
    def pull(self) -> float: ...
    @property
    def recoil(self) -> float: ...
    @property
    def advance(self) -> float: ...
    @property
    def retreat(self) -> float: ...
    @property
    def uses(self) -> float: ...
    @property
    def backfire(self) -> float: ...
    @property
    def heat_generation(self) -> float: ...
    @property
    def energy_cost(self) -> float: ...
    @property
    def bullets_cost(self) -> float: ...
    @property
    def rockets_cost(self) -> float: ...


class StageLevel(Protocol):
    @property
    def power(self) -> int: ...
    @property
    def stats(self) -> ItemStats: ...


class TransformStage(Protocol):
    @property
    def tier(self) -> StageTier: ...
    @property
    def levels(self) -> abc.Sequence[StageLevel]: ...


class ItemData(Protocol):
    @property
    def id(self) -> ItemID: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> ItemType: ...
    @property
    def element(self) -> ItemElement: ...
    @property
    def tags(self) -> abc.Set[ItemTag]: ...


class HasStages(Protocol):
    @property
    def stages(self) -> abc.Sequence[TransformStage]: ...


class HasStats(Protocol):
    @property
    def stats(self) -> ItemStats: ...
