from collections import abc
from typing import NewType, Protocol, cast as type_cast
from typing_extensions import TypeVar

from supermechs.enums import ModuleSlotName, SideWeaponSlotName, TopWeaponSlotName

__all__ = ("Mech", "MechSlot", "MechSummary")

ItemT = TypeVar("ItemT", infer_variance=True)
MechSlot = NewType("MechSlot", str)


class Mech(Protocol[ItemT]):
    @property
    def torso(self) -> ItemT | None: ...
    @property
    def legs(self) -> ItemT | None: ...
    @property
    def drone(self) -> ItemT | None: ...
    @property
    def charge(self) -> ItemT | None: ...
    @property
    def teleport(self) -> ItemT | None: ...
    @property
    def hook(self) -> ItemT | None: ...
    @property
    def shield(self) -> ItemT | None: ...
    @property
    def perk(self) -> ItemT | None: ...

    def __getitem__(self, name: MechSlot, /) -> ItemT | None: ...
    def iter_items(self) -> abc.Iterator[ItemT]: ...
    def side_weapons(self) -> abc.Iterator[ItemT | None]:
        return (self[key] for key in type_cast("abc.Iterable[MechSlot]", SideWeaponSlotName))

    def top_weapons(self) -> abc.Iterator[ItemT | None]:
        return (self[key] for key in type_cast("abc.Iterable[MechSlot]", TopWeaponSlotName))

    def modules(self) -> abc.Iterator[ItemT | None]:
        return (self[key] for key in type_cast("abc.Iterable[MechSlot]", ModuleSlotName))


class MechSummary(Protocol):
    @property
    def weight(self) -> float: ...
    @property
    def hit_points(self) -> float: ...
    @property
    def energy_capacity(self) -> float: ...
    @property
    def regeneration(self) -> float: ...
    @property
    def heat_capacity(self) -> float: ...
    @property
    def cooling(self) -> float: ...
    @property
    def physical_resistance(self) -> float: ...
    @property
    def explosive_resistance(self) -> float: ...
    @property
    def electric_resistance(self) -> float: ...
    @property
    def bullets_capacity(self) -> float: ...
    @property
    def rockets_capacity(self) -> float: ...
    @property
    def walk(self) -> float: ...
    @property
    def jump(self) -> float: ...
