level_percents = [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 20]
hit_points = [0, 10, 30, 60, 90, 120, 150, 180, 220, 260, 300, 350]

[[stats]]
key = "weight"
beneficial = false

[[stats]]
key = "health"
buff = "+HP"

[[stats]]
key = "eneCap"
buff = "+%"

[[stats]]
key = "eneReg"
buff = "+%"

[[stats]]
key = "heaCap"
buff = "+%"

[[stats]]
key = "heaCol"
buff = "+%"

[[stats]]
key = "bulletsCap"

[[stats]]
key = "rocketsCap"

[[stats]]
key = "phyRes"
buff = "resist%"

[[stats]]
key = "expRes"
buff = "resist%"

[[stats]]
key = "eleRes"
buff = "resist%"

[[stats]]
key = "phyDmg"
buff = "+%"

[[stats]]
key = "phyResDmg"

[[stats]]
key = "expDmg"
buff = "+%"

[[stats]]
key = "heaDmg"
buff = "+%"

[[stats]]
key = "heaCapDmg"

[[stats]]
key = "heaColDmg"

[[stats]]
key = "expResDmg"

[[stats]]
key = "eleDmg"
buff = "+%"

[[stats]]
key = "eneDmg"
buff = "+%"

[[stats]]
key = "eneCapDmg"

[[stats]]
key = "eneRegDmg"

[[stats]]
key = "eleResDmg"

[[stats]]
key = "range"

[[stats]]
key = "push"

[[stats]]
key = "pull"

[[stats]]
key = "recoil"

[[stats]]
key = "retreat"

[[stats]]
key = "advance"

[[stats]]
key = "walk"

[[stats]]
key = "jump"

[[stats]]
key = "uses"

[[stats]]
key = "backfire"
beneficial = false
buff = "-%"

[[stats]]
key = "heaCost"
beneficial = false

[[stats]]
key = "eneCost"
beneficial = false

[[stats]]
key = "bulletsCost"
beneficial = false

[[stats]]
key = "rocketsCost"
beneficial = false
